version: '2'

services:
   influxdb:
     image: influxdb
     ports:
       - "8086:8086"
     restart: always

   grafana:
     depends_on:
       - influxdb
     image: grafana/grafana
     ports:
       - "3000:3000"
     restart: always
     environment:
       GF_SERVER_ROOT_URL: "http://localhost"
       GF_SECURITY_ADMIN_PASSWORD: "zadara"

