$bootstrap = <<SCRIPT
/vagrant/ubuntu_prereqs.sh
cd /vagrant && ./run.sh
SCRIPT

Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu/trusty64"
  config.vm.box = "minimal/trusty64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 8086, host: 8086
  config.vm.provision "shell", inline: $bootstrap, privileged: true
end
