version: '3'

services:
  find:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "9022:22"
    volumes:
    - /tmp/av_logs:/export/av_logs
    - /tmp/av_quar:/export/av_quar
    - /tmp/av_vol-a:/export/vol-a
    - /tmp/av_vol-b:/export/vol-b
    environment:
      LOG_PATH: "/export/av_logs"
      QUAR_PATH: "/export/av_quar"
      SCAN_PATH: "/export/vol-a /export/vol-b /export/vol-c"
      MANIFEST_LINES: "1000"
      CLAM_MODE: "find"
      SSH_SERVICE: "enabled"
#      FIND_EXTRA: "-not -name *.ignore"
      FIND_EXTRA: '! \( -name *.ignore -o -name *.ignore2 -o -name "a b" \)'
      FIND_CRON: "10 * * * *"
      VPSA_ACCESSKEY: "NV4JE12C9FF9H5I5T4S9-3857"
      VPSA_IP: "172.29.224.100"
  av1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "9023:22"
    volumes:
    - /tmp/av_logs:/export/av_logs
    - /tmp/av_quar:/export/av_quar
    - /tmp/av_vol-a:/export/vol-a
    - /tmp/av_vol-b:/export/vol-b
    environment:
      LOG_PATH: "/export/av_logs"
      QUAR_PATH: "/export/av_quar"
      SCAN_PATH: "/export/vol-a /export/vol-b"
      CLAM_MODE: "av"
      SSH_SERVICE: "enabled"
      PROXY_SERVER: "127.0.0.1"
      PROXY_PORT: "3214"
      SCAN_CRON: "20 * * * *"
  av2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "9024:22"
    volumes:
    - /tmp/av_logs:/export/av_logs
    - /tmp/av_quar:/export/av_quar
    - /tmp/av_vol-a:/export/vol-a
    - /tmp/av_vol-b:/export/vol-b
    environment:
      LOG_PATH: "/export/av_logs"
      QUAR_PATH: "/export/av_quar"
      SCAN_PATH: "/export/vol-a /export/vol-b"
      CLAM_MODE: "av"
      SSH_SERVICE: "enabled"
      SCAN_THREADS: "2"
      SCAN_CRON: "30 * * * *"
