FROM alpine:3.12

LABEL maintainer="Zadara Storage <support@zadarastorage.com>" \
      vendor="Zadara Storage" \
      description="FIO Performance filltest container"

RUN \
    apk add --no-cache \
      fio

COPY fio-fill.job /fio-fill.job

ENTRYPOINT ["/bin/sh"]
CMD ["-c","/usr/bin/fio fio-fill.job --filename $(mount | awk '/xfs/{f=$3;print f}' | sed 's@$@/fill@g' | paste -sd ':' -)"]
