FROM ubuntu:20.04

LABEL maintainer="Zadara Storage <support@zadarastorage.com>" \
      vendor="Zadara Storage" \
      description="FIO Performance filltest container"

RUN apt-get update && \
    apt-get install -y \
      fio && \
    apt-get clean

COPY fio-fill.job /fio-fill.job

ENTRYPOINT ["/bin/sh"]
CMD ["-c","/usr/bin/fio fio-fill.job --filename $(mount | awk '/xfs/{f=$3;print f}' | sed 's@$@/fill@g' | paste -sd ':' -)"]
